### PR TITLE
fix for node 0.10

### PR DESCRIPTION
**Pull request by revington**
After #16 tests for 0.10 does not pass.

### CODE REVIEW

**Comment by cusspvz** [comment]
Naaiiicceeeee!!!! :D 

Seems right to me! Is this RTM?

**Comment by revington** [comment]
RTM? What does that mean?

**Comment by cusspvz** [comment]
Ready to merge. Sorry.

**Comment by revington** [comment]
ah! I did not know what RTM meant.
Well, it is up to you if it is ready to merge. It passes the tests.
Regarding the versions tested, is there any reason to test 4.0 or 4.1 and not 4.2.4 LTS?
LTS are listed here https://github.com/nodejs/LTS.

I'm trying to figure out why 4.0 is failing.

**Comment by revington** [comment]
aha, the problem of test `test/specific/issue-15.test.js` and node v4.0.0 is node v4.0.0 itself.
if you change the line 
```
server = proxiedHttp.createServer(function handler(req, res) {
```
for 
```
server = http.createServer(function handler(req, res) {
```
it will break anyway.

**Comment by cusspvz** [comment]
> Regarding the versions tested, is there any reason to test 4.0 or 4.1 and not 4.2.4 LTS?

Nope, just copied from another repo I had here laying around that was created before the `4.2 LTS`. Gonna update them all to test LTS only.

> I'm trying to figure out why 4.0 is failing.
> aha, the problem of test test/specific/issue-15.test.js and node v4.0.0 is node v4.0.0 itself.

I don't have so sure of that, because I already have `http` and `net` tests that are working, could it be the way you're setting it up?

**Comment by cusspvz** [comment]
Thanks!! :)

**Comment by revington** [comment]
Hey, 
Forget about my comment 
> aha, the problem of test test/specific/issue-15.test.js and node v4.0.0 is node v4.0.0 itself.  

I already removed that comment. While I've been testing the stuff I get into that scenario but just because something was wrong in my setup. 

You're welcome

**Pull request merged**
